export const appTypes = {
	TEMPLATE_REQUEST: 'USER|TEMPLATE_REQUEST',
	GET_QUIZ_OPTIONS_SUCCESS: 'USER|GET_QUIZ_OPTIONS_SUCCESS',
	GET_QUIZ_OPTIONS_FAILED: 'USER|TEMPLATE_FAILED',
	GET_QUIZ_OPTIONS: 'USER|GET_QUIZ_OPTIONS',
	SELECT_QUIZ_LEVEL: 'USER|SELECT_QUIZ_LEVEL',
	TRIGGER_QUIZ: 'USER|TRIGGER_QUIZ',
	ADD_HOVERED_CELL_POS: 'USER|ADD_HOVERED_CELL_POS'
}
